#!/usr/bin/env bash

# shellcheck disable=1090,1091,2046,2068,2086,2206

set -aeuo pipefail

_realpath() {
  if command -v python3 >/dev/null 2>&1; then
    python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "$1"
  elif command -v greadlink >/dev/null 2>&1; then
    greadlink -f "$1"
  elif command -v realpath >/dev/null 2>&1; then
    realpath -m "$1" 2>/dev/null || realpath "$1"
  else
    perl -MCwd -e 'print Cwd::abs_path(shift)' "$1"
  fi
}

INSTALLDIR=$(_realpath "${INSTALLDIR:-$PWD/conda}")

# In all functions, make variables local unless they are either intended for global use, or set in
# a subshell that exits at the end of the function.

cachedir() {
  (
    env_activate base
    echo $CONDA_PREFIX/cache
  )
}

env_file() {
  local name=$1
  if [ "$(uname -s)" = "Darwin" ] && [ -f "envs/$name.osx.yaml" ]; then
    echo "envs/$name.osx.yaml"
  else
    echo "envs/$name.yaml"
  fi
}

cuda_command_file() {
  local path val
  val=$CUDA_SCRIPT
  path=$val
  test -e "$path" || path=$(dirname "$(_realpath "$0")")/cuda/$val
  echo "$path"
}

cuda_release() {
  (
    if ! command -v module >/dev/null 2>&1; then
      return 0
    fi
    source "$(cuda_command_file)"
    if ! command -v nvcc >/dev/null 2>&1; then
      return 0
    fi
    nvcc --version | grep release | sed -E 's/^.*release ([0-9]+).*/\1/'
  )
}

env_activate() {
  local env
  env=$1
  source $INSTALLDIR/etc/profile.d/mamba.sh
  # Activation scripts shipped with conda packages may contain statements either expanding undefined
  # variables or exiting with error status, so temporarily disable the checks for these conditions,
  # then enable again.
  set +eu
  mamba activate $env
  set -eu
}

env_exists() {
  local d name x
  name=$1
  d=$INSTALLDIR/envs
  mkdir -p $d
  for x in $(find $d -maxdepth 1 -mindepth 1 -type d | sort); do
    if [[ $(basename $x) == "$name" ]]; then
      msg Found existing conda environment: $name
      return 0
    fi
  done
  return 1
}

install_conda() {
  local installer url ver
  if [[ -d $INSTALLDIR ]]; then
    msg Found existing conda installation: $INSTALLDIR
    return
  fi
  local platform arch
  ver=26.1.1-3
  platform=$(uname -s)
  arch=$(uname -m)
  if [ "$platform" = "Darwin" ]; then
    platform=MacOSX
  fi
  installer=Miniforge3-$ver-$platform-$arch.sh
  url=https://github.com/conda-forge/miniforge/releases/download/$ver/$installer
  msg Installing conda
  if command -v wget >/dev/null 2>&1; then
    wget -nv "$url"
  else
    curl -L -o "$installer" "$url"
  fi
  bash "$installer" -bfp "$INSTALLDIR"
  rm -v "$installer"
}

install_devpkgs_maybe() {
  local name
  if [ -n "${EAGLEDEV:-}" ]; then
    name=$1
    msg Installing dev packages into environment: $name
    (
      env_activate $name
      mamba env update ${MAMBAFLAGS[@]} --file envs/dev.yaml
    )
  fi
}

msg() {
  echo -e "=> $*"
}

parse_kvargs() {
  local arg key val IFS
  for arg in "$@"; do
    IFS="="
    read -r key val <<<"$arg"
    case "$key" in
      cudascript)
        CUDA_SCRIPT="$val"
        ;;
      *)
        eval "$key=\"$val\""
        ;;
    esac
  done
  if [ -z "${CUDA_SCRIPT:-}" ]; then
    echo "Argument cudascript= missing"
    exit 1
  fi
}

prep_env() {
  local args name
  name=$1
  args=(${MAMBAFLAGS[@]} --file $(env_file "$name") --name $name)
  (
    env_activate base
    if env_exists $name; then
      msg Updating environment: $name
      mamba env update ${args[@]} | { grep --line-buffered -v "Requirement already satisfied" || true; }
    else
      msg Creating environment: $name
      mamba env create ${args[@]}
    fi
  )
  install_devpkgs_maybe $name
  # When runtime virtual environments are activated, set XDG_CACHE_HOME so that pip caches package
  # files in the runtime area, rather than in the user's home directory, which might impact their
  # quota. When deactivated, environments should reset or unset this value, as appropriate.
  #
  # Always run this step to re-create these scripts, as downstream steps will *append* to them.
  (
    env_activate $name
    dir_activate=$CONDA_PREFIX/etc/conda/activate.d
    mkdir -pv $dir_activate
    cat <<EOF >$dir_activate/eagle.sh
if [ -n "${XDG_CACHE_HOME:-}" ]; then
  export EAGLE_OLD_XDG_CACHE_HOME=\$XDG_CACHE_HOME
fi
export XDG_CACHE_HOME=$(cachedir)
EOF
    dir_deactivate=$CONDA_PREFIX/etc/conda/deactivate.d
    mkdir -pv $dir_deactivate
    cat <<EOF >$dir_deactivate/eagle.sh
unset XDG_CACHE_HOME
if [ -n "${EAGLE_OLD_XDG_CACHE_HOME:-}" ]; then
  export XDG_CACHE_HOME=\$EAGLE_OLD_XDG_CACHE_HOME
  unset EAGLE_OLD_XDG_CACHE_HOME
fi
EOF
  )
}

prep_env_base() {
  local name
  name=base
  (
    env_activate $name
    msg Updating environment: $name
    mamba env update ${MAMBAFLAGS[@]} --file $(env_file "$name")
    install_devpkgs_maybe $name
  )
}

prep_env_data() {
  local name
  name=data
  prep_env $name
  # Add logic to the [de]activation scripts to silence a run-time complaint:
  (
    env_activate $name
    dir_activate=$CONDA_PREFIX/etc/conda/activate.d
    mkdir -pv $dir_activate
    # NB: Append to the existing script:
    cat <<EOF >>$CONDA_PREFIX/etc/conda/activate.d/eagle.sh
if [ -n "${FI_PSM3_UUID:-}" ]; then
  export EAGLE_OLD_FI_PSM3_UUID=\$FI_PSM3_UUID
fi
export FI_PSM3_UUID=eagle
EOF
    dir_deactivate=$CONDA_PREFIX/etc/conda/deactivate.d
    mkdir -pv $dir_deactivate
    # NB: Append to the existing script:
    cat <<EOF >>$dir_deactivate/eagle.sh
unset FI_PSM3_UUID
if [ -n "${EAGLE_OLD_FI_PSM3_UUID:-}" ]; then
  export FI_PSM3_UUID=\$EAGLE_OLD_FI_PSM3_UUID
  unset EAGLE_OLD_FI_PSM3_UUID
fi
EOF
  )
}

prep_env_inference() {
  local name
  name=inference
  prep_env $name
  write_anemoi_activation_scripts $name
}

prep_env_prewxvx() {
  prep_env prewxvx
}

prep_env_training() {
  local name
  name=training
  prep_env $name
  write_anemoi_activation_scripts $name
}

prep_env_visualization() {
  prep_env visualization
}

prep_env_wxvx() {
  prep_env wxvx
}

write_anemoi_activation_scripts() {
  local name=$1
  (
    env_activate $name
    # NB: Append to the existing script:
    cat <<EOF >>$CONDA_PREFIX/etc/conda/activate.d/eagle.sh
modules="\$(module --terse list 2>/dev/null | grep -v 'No modules loaded' | tr '\n' ' ')"
if [ -n "\$modules" ]; then
  export EAGLE_OLD_MODULES="\$modules"
fi
$(cat $(cuda_command_file))
EOF
    # NB: Append to the existing script:
    cat <<EOF >>$CONDA_PREFIX/etc/conda/deactivate.d/eagle.sh
module purge 2>/dev/null
if [ -n "${EAGLE_OLD_MODULES:-}" ]; then
  module load \$EAGLE_OLD_MODULES
  unset EAGLE_OLD_MODULES
fi
EOF
  )
}

parse_kvargs $@
install_conda
CONDA_OVERRIDE_CUDA=$(cuda_release)
MAMBAFLAGS=(--log-level error --yes)
MAMBA_ROOT_PREFIX=$INSTALLDIR
XDG_CACHE_HOME=$(cachedir)
export CONDA_OVERRIDE_CUDA MAMBA_ROOT_PREFIX XDG_CACHE_HOME
if [ "$(uname -s)" = "Darwin" ]; then
  environments=(base data inference prewxvx training visualization)
  echo "=> Darwin detected: skipping wxvx environment because required package met2go is unavailable on macOS"
else
  environments=(base data inference prewxvx training visualization wxvx)
fi
for name in ${environments[@]}; do
  time prep_env_$name
done
msg Done
